# Generated by Django 4.2 on 2023-04-16 00:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("service", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicerequest",
            name="staff",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staff_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("SB", "Submitted"),
                    ("SH", "Shipping"),
                    ("RS", "Repair"),
                    ("D", "Delivered"),
                ],
                default="SB",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="title",
            field=models.CharField(default=" ", max_length=250),
        ),
    ]
