# Generated by Django 4.2 on 2023-04-16 00:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0002_servicerequest_staff_servicerequest_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicerequest",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
